name: Manual Generate Combined Script

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for the generated combined script'
        required: true
        default: 'Update combined_script.py'

jobs:
  run-generate-combined:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run generate_combined.py
        run: python generate_combined.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add combined_script.py
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
